version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: upload-sas-mongodb
    restart: always

    ports:
      - "27018:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: upload_sas_demo

    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: upload-sas-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  jaeger-web:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-web
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: collector
    command: ["--config=/etc/otelcol-contrib/config.yml"]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
    volumes:
      - ./collector-config.yml:/etc/otelcol-contrib/config.yml
    depends_on:
      - jaeger-web

volumes:
  mongo-data:
  redis-data: